---
# tasks file for daimon.sysbase
  - name: 安装系统软件包
    yum: name={{ item }} state=installed enablerepo=epel
    become: true
    with_items:
      - https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-{{ansible_distribution_major_version}}-x86_64/pgdg-centos96-9.6-3.noarch.rpm
      - http://centos{{ansible_distribution_major_version}}.iuscommunity.org/ius-release.rpm
      - git2u
      - nginx
      - supervisor
      - libtiff-devel
      - libjpeg-devel
      - libzip-devel
      - freetype-devel
      - lcms2-devel
      - libwebp-devel
      - tcl-devel
      - tk-devel
      - haproxy
      - iftop
      - tcpdump
      - bc
      - pycrypto
      - gcc
      - python-devel
      - openssl
      - openssl-devel
      - lsof
  - name: 防火墙启动
    service: name=firewalld state=started enabled=yes
    when:
      - ansible_distribution_major_version == "7"
    ignore_errors: True
  - name: 防火墙配置
    template: >
      src=public.xml.j2 dest=/etc/firewalld/zones/public.xml
    when:
      - ansible_distribution_major_version == "7"
    notify: restart firewalld

